const IconList = [
  'home',
  'quill',
  'camera',
  'spinner',
  'menu',
  'heart',
  'plus',
  'minus',
  'arrow-up-left',
  'arrow-up',
  'arrow-up-right',
  'arrow-right',
  'arrow-down-right',
  'arrow-down',
  'arrow-down-left',
  'arrow-left',
  'mail',
  'facebook',
  'youtube',
  'twitch',
  'github',
] as const;

export default IconList;
